#!/usr/bin/env python3
"""Embeds the PNGs in src/images/ as byte arrays into src/images.generated.h.

Run automatically by CMake (see CMakeLists.txt) before compiling; the raw .png
files are the checked-in source of truth, the header is a gitignored build
artifact.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
IMAGES_DIR = os.path.join(ROOT, "src", "images")
OUT_PATH = os.path.join(ROOT, "src", "images.generated.h")

# (source file, C identifier)
IMAGES = [
    ("icon_trophies.png", "IconTrophies"),
    ("icon_trophies_glow.png", "IconTrophiesGlow"),
]


def emit_array(f, ident, data):
    f.write(f"inline constexpr unsigned char k{ident}PNG[] = {{\n")
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        f.write("    " + ", ".join(str(b) for b in chunk) + ",\n")
    f.write("};\n")
    f.write(f"inline constexpr unsigned int k{ident}PNGSize = sizeof(k{ident}PNG);\n\n")


def main():
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/gen-images.py from the PNGs in src/images/. Do not edit",
        "// by hand or commit this file directly - it is rebuilt on every CMake configure.",
        "",
        "namespace eternalsonata {",
        "",
    ]

    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
        for filename, ident in IMAGES:
            with open(os.path.join(IMAGES_DIR, filename), "rb") as fin:
                data = fin.read()
            emit_array(out, ident, data)
        out.write("}  // namespace eternalsonata\n")

    print(f"+ wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
