#!/usr/bin/env python3
"""Write src/assets/shift_jis_table.inc: every BMP character cp932 encodes
outside ASCII, as {unicode, shift_jis} pairs sorted by code point, for
assets::EncodeShiftJis. cp932 rather than strict Shift-JIS because the game's
Japanese text is Microsoft flavoured (it uses U+FF5E for the wave dash).

usage: python scripts/gen-shift-jis-table.py
"""
import os

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "assets", "shift_jis_table.inc")

pairs = []
for cp in range(0x80, 0x10000):
    if 0xD800 <= cp < 0xE000:
        continue
    try:
        b = chr(cp).encode("cp932")
    except UnicodeEncodeError:
        continue
    pairs.append((cp, int.from_bytes(b, "big")))

with open(OUT, "w", newline="\n") as f:
    f.write("// Generated by scripts/gen-shift-jis-table.py; do not edit.\n")
    for i in range(0, len(pairs), 6):
        f.write(" ".join(f"{{0x{u:04X}, 0x{s:04X}}}," for u, s in pairs[i:i + 6]) + "\n")
print(f"{len(pairs)} pairs")
