#!/usr/bin/env python3
"""Embeds res/bgm.wma (WMA, the format the SDK plays) as a byte array into src/bgm.generated.h.

Run automatically by CMake (see CMakeLists.txt); the header is a gitignored
build artifact.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SRC_PATH = os.path.join(ROOT, "res", "bgm.wma")
OUT_PATH = os.path.join(ROOT, "src", "bgm.generated.h")


def main():
    data = open(SRC_PATH, "rb").read() if os.path.isfile(SRC_PATH) else b""
    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("#pragma once\n\n// Generated by scripts/gen-audio.py from res/bgm.wma.\n\n")
        out.write("namespace eternalsonata {\n\n")
        out.write("inline constexpr unsigned char kBgm[] = {\n")
        for i in range(0, len(data), 24):
            out.write("    " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
        out.write("    0};\n")
        out.write(f"inline constexpr unsigned int kBgmSize = {len(data)};\n\n")
        out.write("}  // namespace eternalsonata\n")
    print(f"+ wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
