#!/usr/bin/env python3
"""Embeds the PNGs in src/images/ and res/ as byte arrays into src/images.generated.h.

Every res/*.png is also listed by file stem in kResImages, so code can look up
art that a checkout may not have.

Run automatically by CMake (see CMakeLists.txt) before compiling; the raw .png
files are the checked-in source of truth, the header is a gitignored build
artifact.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
IMAGES_DIR = os.path.join(ROOT, "src", "images")
RES_DIR = os.path.join(ROOT, "res")
OUT_PATH = os.path.join(ROOT, "src", "images.generated.h")

# (source file, C identifier)
IMAGES = [
    ("icon_trophies.png", "IconTrophies"),
    ("icon_trophies_glow.png", "IconTrophiesGlow"),
]


def emit_array(f, ident, data):
    f.write(f"inline constexpr unsigned char k{ident}PNG[] = {{\n")
    for i in range(0, len(data), 20):
        chunk = data[i:i + 20]
        f.write("    " + ", ".join(str(b) for b in chunk) + ",\n")
    f.write("};\n")
    f.write(f"inline constexpr unsigned int k{ident}PNGSize = sizeof(k{ident}PNG);\n\n")


def res_ident(filename):
    stem = os.path.splitext(filename)[0]
    return "Res" + "".join(w.capitalize() for w in stem.replace("-", "_").split("_"))


def main():
    lines = [
        "#pragma once",
        "",
        "// Generated by scripts/gen-images.py from the PNGs in src/images/ and res/.",
        "// Do not edit by hand or commit this file directly - it is rebuilt on every",
        "// CMake configure.",
        "",
        "namespace eternalsonata {",
        "",
    ]

    res = []
    if os.path.isdir(RES_DIR):
        res = sorted(f for f in os.listdir(RES_DIR) if f.lower().endswith(".png"))

    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
        for filename, ident in IMAGES:
            with open(os.path.join(IMAGES_DIR, filename), "rb") as fin:
                data = fin.read()
            emit_array(out, ident, data)

        entries = []
        for filename in res:
            ident = res_ident(filename)
            with open(os.path.join(RES_DIR, filename), "rb") as fin:
                emit_array(out, ident, fin.read())
            stem = os.path.splitext(filename)[0]
            entries.append(f'    {{"{stem}", k{ident}PNG, k{ident}PNGSize}},')
        entries.append("    {nullptr, nullptr, 0},")

        out.write("struct ResImage {\n")
        out.write("  const char* name;\n")
        out.write("  const unsigned char* data;\n")
        out.write("  unsigned int size;\n")
        out.write("};\n\n")
        out.write("// Every res/*.png by file stem, ending in a null entry.\n")
        out.write("inline constexpr ResImage kResImages[] = {\n")
        out.write("\n".join(entries) + "\n")
        out.write("};\n\n")
        out.write("}  // namespace eternalsonata\n")

    print(f"+ wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
