#!/usr/bin/env python3
"""Compile src/guest_data/ps3/text/ into the PS3 item and magic text blocks
(src/engine/ps3_item_text.generated.inc), each tagged with the 360 block its
readers are pointed away from.

usage:
    python scripts/gen-ps3-item-text.py [output]
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from guest_data import encode_btx, read_text  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TEXT_DIR = os.path.join(ROOT, "src", "guest_data", "ps3", "text")
OUT = os.path.join(ROOT, "src", "engine", "ps3_item_text.generated.inc")
FILES = ["items", "item_descriptions", "party_skills", "party_skill_help"]


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else OUT
    lines = ["// Generated by scripts/gen-ps3-item-text.py from src/guest_data/ps3/text. Do not edit."]
    names = []
    for i, name in enumerate(FILES):
        address, langs = read_text(os.path.join(TEXT_DIR, name + ".txt"))
        blob = encode_btx(langs)
        lines.append("constexpr uint8_t kPs3TextBlock%d[] = {" % i)
        for k in range(0, len(blob), 32):
            lines.append(",".join(str(b) for b in blob[k:k + 32]) + ",")
        lines.append("};")
        names.append("{0x%08Xu, kPs3TextBlock%d, sizeof(kPs3TextBlock%d)}" % (address, i, i))
    lines.append("constexpr Ps3TextBlock kPs3TextBlocks[] = {%s};" % ", ".join(names))
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
