#!/usr/bin/env python3
"""Embeds res/lang/*.toml into src/lang.generated.h, English first.

Run by CMake before compiling; the .toml files are the checked-in source of
truth, the header is a gitignored build artifact.
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
LANG_DIR = os.path.join(ROOT, "res", "lang")
OUT_PATH = os.path.join(ROOT, "src", "lang.generated.h")


def main():
    codes = sorted(os.path.splitext(f)[0] for f in os.listdir(LANG_DIR) if f.endswith(".toml"))
    codes.sort(key=lambda c: c != "en")
    with open(OUT_PATH, "w", newline="\n") as out:
        out.write("#pragma once\n\n// Generated by scripts/gen-lang.py from res/lang/*.toml.\n\n")
        out.write("namespace eternalsonata {\n\n")
        for i, code in enumerate(codes):
            with open(os.path.join(LANG_DIR, code + ".toml"), "rb") as f:
                data = f.read()
            out.write(f"inline constexpr char kLang{i}[] = {{\n")
            for j in range(0, len(data), 20):
                out.write("    " + ", ".join(str(b if b < 128 else b - 256) for b in data[j:j + 20]) + ",\n")
            out.write("};\n\n")
        out.write("struct LangFile {\n  const char* code;\n  const char* text;\n  unsigned int size;\n};\n\n")
        out.write("inline constexpr LangFile kLangFiles[] = {\n")
        for i, code in enumerate(codes):
            out.write(f'    {{"{code}", kLang{i}, sizeof(kLang{i})}},\n')
        out.write("};\n\n}  // namespace eternalsonata\n")
    print(f"+ wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
