#!/usr/bin/env python3
"""Write src/engine/achievement_text.h: every achievement string as code.

Runs `rexglue init achievements` once per language the xex's XDBF holds
and turns the TOMLs into constexpr tables, so nothing reads the XDBF for
text. PAL holds English, German, French, Spanish and Italian; Japanese is
only in the JP release's xex and falls back to English until it is dumped.

    python scripts/gen-achievement-text.py assets/default.xex src/engine/achievement_text.h
"""
import os
import subprocess
import sys
import tempfile
import tomllib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
REXGLUE = os.path.join(ROOT, "sdk", "bin", "rexglue.exe" if os.name == "nt" else "rexglue")

# XLanguage id and table name, for the languages PAL's XDBF holds.
LANGUAGES = [(1, "English"), (3, "German"), (4, "French"), (5, "Spanish"), (6, "Italian")]


def dump(xex, language, out_dir):
    # The parent command's required options apply to the subcommand too.
    subprocess.run([REXGLUE, "init", "--project-name", "x", "--xex-path", xex,
                    "achievements", xex, out_dir, "--language", str(language)],
                   check=True, capture_output=True)
    with open(os.path.join(out_dir, "achievements.toml"), "rb") as f:
        return tomllib.load(f)["achievements"]


def literal(text):
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    xex, dst = sys.argv[1:]
    tables = {}
    with tempfile.TemporaryDirectory() as tmp:
        for language, name in LANGUAGES:
            tables[name] = dump(xex, language, os.path.join(tmp, str(language)))

    base = tables["English"]
    for name, rows in tables.items():
        if [r["id"] for r in rows] != [r["id"] for r in base]:
            sys.exit(f"{name} lists different achievements")

    out = [
        "// eternalsonata - ReXGlue Recompiled Project",
        "//",
        "// Generated by scripts/gen-achievement-text.py from the PAL default.xex.",
        "// Japanese falls back to English until the JP release's xex is dumped.",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <span>",
        "#include <string_view>",
        "",
        "namespace eternalsonata {",
        "",
        "struct AchievementRecord {",
        "  uint32_t id;",
        "  uint32_t gamerscore;",
        "  uint32_t image_id;",
        "  uint32_t flags;",
        "};",
        "",
        "struct AchievementText {",
        "  uint32_t id;",
        "  std::string_view label;",
        "  std::string_view description;",
        "  std::string_view unachieved_description;",
        "};",
        "",
        "inline constexpr AchievementRecord kAchievements[] = {",
    ]
    for r in base:
        out.append(f"    {{{r['id']}, {r['gamerscore']}, {r['image_id']}, {r['flags']}}},")
    out.append("};")
    for name, rows in tables.items():
        out += ["", f"inline constexpr AchievementText kAchievementText{name}[] = {{"]
        for r in rows:
            out.append(f"    {{{r['id']},")
            out.append(f"     {literal(r['label'])},")
            out.append(f"     {literal(r['description'])},")
            out.append(f"     {literal(r['unachieved_description'])}}},")
        out.append("};")
    out += [
        "",
        "// Indexed by XLanguage id.",
        "inline constexpr std::span<const AchievementText> kAchievementTextByLanguage[] = {",
        "    {},",
        "    kAchievementTextEnglish,",
        "    kAchievementTextEnglish,  // Japanese",
    ]
    out += [f"    kAchievementText{name}," for _, name in LANGUAGES[1:]]
    out += ["};", "", "}  // namespace eternalsonata", ""]

    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"{dst}: {len(base)} achievements, {len(tables)} languages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
