#!/usr/bin/env python3
"""Write the PS3 enemy table as C++ source (src/engine/ps3_enemy_table.generated.inc).

The battle reads enemy n from 80 byte records at off_82024100 (281 on the
360) and the PS3's own (0x51052C, 336); see docs/ps3-assets.md section 4.
Words 1..6 are model name pointers; the rest are plain values.

Without the EBOOT the table is written empty, and PS3 mode keeps the 360's.

usage:
    python scripts/ps3_enemy_table.py [EBOOT.elf [output]]
"""
import os
import struct
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TABLE_VA = 0x51052C
RECORD = 80
OUT = os.path.join(ROOT, "src", "engine", "ps3_enemy_table.generated.inc")
EBOOT = os.path.join(ROOT, "assets", "EBOOT.elf")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else EBOOT
    out = sys.argv[2] if len(sys.argv) > 2 else OUT
    if not os.path.isfile(path):
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("// No PS3 EBOOT.elf at build time: empty.\n")
        print("warning: %s not found, wrote an empty %s" % (path, out))
        return
    elf = open(path, "rb").read()
    phoff = struct.unpack(">Q", elf[0x20:0x28])[0]
    phes, phnum = struct.unpack(">HH", elf[0x36:0x3A])
    segments = []
    for i in range(phnum):
        o = phoff + i * phes
        kind, _, offset, va, _, filesz, _ = struct.unpack(">IIQQQQQ", elf[o:o + 48])
        if kind == 1:
            segments.append((va, offset, filesz))

    def file_offset(va):
        for start, offset, size in segments:
            if start <= va < start + size:
                return offset + va - start
        raise ValueError("unmapped address %#x" % va)

    def cstring(va):
        o = file_offset(va)
        return elf[o:elf.index(0, o)].decode("ascii")

    table = file_offset(TABLE_VA)
    lines = [
        "// Generated by scripts/ps3_enemy_table.py from the PS3 EBOOT. Do not edit.",
        "// {word 0, model names (words 1..6), words 7..19}",
    ]
    count = 0
    while True:
        words = struct.unpack(">20I", elf[table + RECORD * count:table + RECORD * (count + 1)])
        if words[0] >> 16 != count + 1:
            break
        names = ", ".join('"%s"' % cstring(w) for w in words[1:7])
        rest = ", ".join("0x%X" % w for w in words[7:])
        lines.append("{0x%08X, {%s}, {%s}}," % (words[0], names, rest))
        count += 1
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d enemies to %s" % (count, out))


if __name__ == "__main__":
    main()
