#!/usr/bin/env python3
"""Write the PS3's starting stats for characters 11 and 12 as C++ source
(src/engine/ps3_party_template.inc).

sub_821E7138 starts every character from a 136 byte record of the table at
0x82016150, ten on the 360. The PS3 keeps the same records at 0x479A98,
twelve of them: Crescendo and Serenade follow March.

The output is committed; the build does not run this.

usage:
    python scripts/ps3_party_template.py EBOOT.elf [output]
"""
import os
import struct
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TABLE_VA = 0x479A98
RECORD = 136
OUT = os.path.join(ROOT, "src", "engine", "ps3_party_template.inc")


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    path = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else OUT
    elf = open(path, "rb").read()
    phoff = struct.unpack(">Q", elf[0x20:0x28])[0]
    phes, phnum = struct.unpack(">HH", elf[0x36:0x3A])
    segments = []
    for i in range(phnum):
        o = phoff + i * phes
        kind, _, offset, va, _, filesz, _ = struct.unpack(">IIQQQQQ", elf[o:o + 48])
        if kind == 1:
            segments.append((va, offset, filesz))

    def file_offset(va):
        for start, offset, size in segments:
            if start <= va < start + size:
                return offset + va - start
        raise ValueError("unmapped address %#x" % va)

    table = file_offset(TABLE_VA)
    lines = ["// Generated by scripts/ps3_party_template.py from the PS3 EBOOT."]
    for character in (11, 12):
        record = elf[table + RECORD * (character - 1):table + RECORD * character]
        if struct.unpack(">H", record[:2])[0] != character:
            raise ValueError("record %d does not hold character %d" % (character, character))
        lines.append("{" + ", ".join("0x%02X" % b for b in record) + "},")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote characters 11 and 12 to %s" % out)


if __name__ == "__main__":
    main()
