#!/usr/bin/env python3
"""Write the PS3 hit effect table as C++ source (src/engine/ps3_hit_effect_table.generated.inc).

sub_8218E480 looks up record n (1 based) of unk_82078B00: 25 entries of
{u8 kind, u8 kind, u16 pad, s32 slot, s32 slot}, then two floats. Kind 0 is
an AppKeep.bmd slot, kind 1 a BattleKeep.bop slot, -2 asks for the current
default. The 360 has 111 records, the PS3 119 (0x410F00); see
docs/ps3-assets.md section 4. Slots are written in the 360's numbering,
which the kept AppKeep.bmd and the reordered BattleKeep use.

Without the EBOOT the table is written empty, and PS3 mode keeps the 360's.

usage:
    python scripts/ps3_hit_effect_table.py [EBOOT.elf [output]]
"""
import os
import struct
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TABLE_VA = 0x410F00
COUNT = 119
RECORD = 308
ENTRIES = 25
OUT = os.path.join(ROOT, "src", "engine", "ps3_hit_effect_table.generated.inc")
EBOOT = os.path.join(ROOT, "assets", "EBOOT.elf")

# PS3 AppKeep slot -> 360 slot, from the 111 records both releases share.
# Every slot the PS3 table names is one of these.
APPKEEP = {65: 66, 67: 68, 69: 70, 71: 72, 73: 74, 75: 76, 79: 80, 81: 82, 83: 84,
           85: 86, 87: 88, 89: 90, 90: 91, 92: 93}
# The PS3 dropped BattleKeep's 360 slots 26..33 (ps3_battlekeep.cpp).
BATTLEKEEP_DROPPED = 26
BATTLEKEEP_SHIFT = 8


def slot_360(kind, slot, where):
    if slot < 0 or kind not in (0, 1):
        return slot
    if kind == 1:
        return slot + BATTLEKEEP_SHIFT if slot >= BATTLEKEEP_DROPPED else slot
    if slot not in APPKEEP:
        raise SystemExit("%s: AppKeep slot %d has no 360 counterpart" % (where, slot))
    return APPKEEP[slot]


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else EBOOT
    out = sys.argv[2] if len(sys.argv) > 2 else OUT
    if not os.path.isfile(path):
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("// No PS3 EBOOT.elf at build time: empty.\n")
        print("warning: %s not found, wrote an empty %s" % (path, out))
        return
    elf = open(path, "rb").read()
    phoff = struct.unpack(">Q", elf[0x20:0x28])[0]
    phes, phnum = struct.unpack(">HH", elf[0x36:0x3A])
    table = None
    for i in range(phnum):
        o = phoff + i * phes
        kind, _, offset, va, _, filesz, _ = struct.unpack(">IIQQQQQ", elf[o:o + 48])
        if kind == 1 and va <= TABLE_VA < va + filesz:
            table = offset + TABLE_VA - va
    if table is None:
        raise SystemExit("table address not mapped")

    lines = [
        "// Generated by scripts/ps3_hit_effect_table.py from the PS3 EBOOT. Do not edit.",
        "// One record of 77 big endian words per line, slots in 360 numbering.",
    ]
    for n in range(COUNT):
        record = bytearray(elf[table + RECORD * n:table + RECORD * (n + 1)])
        for e in range(ENTRIES):
            at = 12 * e
            for k in range(2):
                kind = record[at + k]
                slot = struct.unpack_from(">i", record, at + 4 + 4 * k)[0]
                where = "record %d entry %d" % (n + 1, e)
                struct.pack_into(">i", record, at + 4 + 4 * k, slot_360(kind, slot, where))
        words = struct.unpack(">77I", record)
        lines.append("{" + ", ".join("0x%X" % w for w in words) + "},")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d records to %s" % (COUNT, out))


if __name__ == "__main__":
    main()
