#!/usr/bin/env python3
"""Write the PS3's shop stock as C++ source (src/engine/ps3_shop_stock.inc).

The PS3 keeps the 360's shop stock table (0x82015CE0, 68 byte records of u16
id, u16 count and 32 items) at 0x47A0F8 as 74 byte records with room for 35
items: restocked shops, new items, and shop 13 (sbi05). Sixteen records, as on
the 360.

The output is committed; the build does not run this.

usage:
    python scripts/ps3_shop_stock.py EBOOT.elf [output]
"""
import os
import struct
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TABLE_VA = 0x47A0F8
RECORD = 74
COUNT = 16
OUT = os.path.join(ROOT, "src", "engine", "ps3_shop_stock.inc")


def main():
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    path = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else OUT
    elf = open(path, "rb").read()
    phoff = struct.unpack(">Q", elf[0x20:0x28])[0]
    phes, phnum = struct.unpack(">HH", elf[0x36:0x3A])
    table = None
    for i in range(phnum):
        o = phoff + i * phes
        kind, _, offset, va, _, filesz, _ = struct.unpack(">IIQQQQQ", elf[o:o + 48])
        if kind == 1 and va <= TABLE_VA < va + filesz:
            table = offset + TABLE_VA - va
    if table is None:
        raise ValueError("unmapped address %#x" % TABLE_VA)
    lines = ["// Generated by scripts/ps3_shop_stock.py from the PS3 EBOOT."]
    for shop in range(1, COUNT + 1):
        record = elf[table + RECORD * (shop - 1):table + RECORD * shop]
        if struct.unpack(">H", record[:2])[0] != shop:
            raise ValueError("record %d does not hold shop %d" % (shop, shop))
        lines.append("{" + ", ".join("0x%02X" % b for b in record) + "},")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d shops to %s" % (COUNT, out))


if __name__ == "__main__":
    main()
