// Generated by scripts/party_relocation_emit.py -- do not edit.
//
// Relocates every per-character array out of the original block, so
// that block can be left poisoned and any site the sweep missed shows
// up as a canary hit rather than as corruption. See the script for the
// layout reasoning.

#include "party_relocation.h"

#include <rex/ppc/context.h>

namespace {

// The new bases belong to party_relocation.h, which owns the guest
// memory they point at. Assert rather than redeclare, so the two
// halves cannot drift apart.
static_assert(eternalsonata::kCharflagsBase == 0x8b001a00,
              "charflags moved; regenerate the relocation hooks");
static_assert(0x8b001a00 + 12 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "charflags (12 * 1 bytes) does not fit the reserved page");
static_assert(eternalsonata::kCharwordsBase == 0x8b001800,
              "charwords moved; regenerate the relocation hooks");
static_assert(0x8b001800 + 24 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "charwords (12 * 2 bytes) does not fit the reserved page");
static_assert(eternalsonata::kPositionBase == 0x8b001900,
              "position moved; regenerate the relocation hooks");
static_assert(0x8b001900 + 48 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "position (12 * 4 bytes) does not fit the reserved page");
static_assert(eternalsonata::kSlotbytesBase == 0x8b000000,
              "slotbytes moved; regenerate the relocation hooks");
static_assert(0x8b000000 + 12 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "slotbytes (12 * 1 bytes) does not fit the reserved page");
static_assert(eternalsonata::kStatsBaseBase == 0x8b000100,
              "stats_base moved; regenerate the relocation hooks");
static_assert(0x8b000100 + 576 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "stats_base (12 * 48 bytes) does not fit the reserved page");
static_assert(eternalsonata::kStatsLiveBase == 0x8b002000,
              "stats_live moved; regenerate the relocation hooks");
static_assert(0x8b002000 + 576 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "stats_live (12 * 48 bytes) does not fit the reserved page");
static_assert(eternalsonata::kTemplateBase == 0x8b001000,
              "template moved; regenerate the relocation hooks");
static_assert(0x8b001000 + 1632 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "template (12 * 136 bytes) does not fit the reserved page");
static_assert(eternalsonata::kRelocatedCharacterCount == 12,
              "the hook table was generated for a different cast size");

}  // namespace

// The hook bodies are looked up by name by the recompiler, so they
// keep external linkage.

// charflags: 0x8243fcfc -> 0x8b001a00
constexpr int32_t kRelocCharflagsDelta = static_cast<int32_t>(0x08bc1d04);

void PartyReloc_charflags_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocCharflagsDelta;
}

// charwords: 0x824400c8 -> 0x8b001800
constexpr int32_t kRelocCharwordsDelta = static_cast<int32_t>(0x08bc1738);

void PartyReloc_charwords_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocCharwordsDelta;
}

// position: 0x8243fc08 -> 0x8b001900
constexpr int32_t kRelocPositionDelta = static_cast<int32_t>(0x08bc1cf8);

void PartyReloc_position_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocPositionDelta;
}

void PartyReloc_position_Shift(PPCRegister& reg) {
    reg.u32 += kRelocPositionDelta;
}

void PartyReloc_position_Unshift(PPCRegister& reg) {
    reg.u32 -= kRelocPositionDelta;
}

// slotbytes: 0x8243fc30 -> 0x8b000000
constexpr int32_t kRelocSlotbytesDelta = static_cast<int32_t>(0x08bc03d0);

void PartyReloc_slotbytes_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocSlotbytesDelta;
}

void PartyReloc_slotbytes_Unshift(PPCRegister& reg) {
    reg.u32 -= kRelocSlotbytesDelta;
}

// stats_base: 0x8243fee8 -> 0x8b000100
constexpr int32_t kRelocStatsBaseDelta = static_cast<int32_t>(0x08bc0218);

void PartyReloc_stats_base_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocStatsBaseDelta;
}

// stats_live: 0x8243fd08 -> 0x8b002000
constexpr int32_t kRelocStatsLiveDelta = static_cast<int32_t>(0x08bc22f8);

void PartyReloc_stats_live_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocStatsLiveDelta;
}

// template: 0x82016150 -> 0x8b001000
constexpr int32_t kRelocTemplateDelta = static_cast<int32_t>(0x08feaeb0);

void PartyReloc_template_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocTemplateDelta;
}

// position loop bound: 0x8243fc30 -> 0x8b001930 (the end of the relocated array, two entries longer)
constexpr int32_t kRelocEndPositionDelta = static_cast<int32_t>(0x08bc1d00);

void PartyRelocEnd_position_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocEndPositionDelta;
}

// stats_base loop bound: 0x824400c8 -> 0x8b000340 (the end of the relocated array, two entries longer)
constexpr int32_t kRelocEndStatsBaseDelta = static_cast<int32_t>(0x08bc0278);

void PartyRelocEnd_stats_base_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocEndStatsBaseDelta;
}

// position -> slotbytes: a walking pointer crossing from one array to
// the next, already carrying the position delta.
void PartyRebase_position_To_slotbytes(PPCRegister& reg) {
    reg.u32 += static_cast<int32_t>(0xffffe6d8);
}
