// Generated by scripts/party_relocation_emit.py -- do not edit.
//
// Relocates the cold per-character arrays out of the way so the hot
// ones can grow from ten to twelve entries in place. See the script
// for the layout reasoning.

#include "party_relocation.h"

#include <rex/ppc/context.h>

namespace {

// The new bases belong to party_relocation.h, which owns the guest
// memory they point at. Assert rather than redeclare, so the two
// halves cannot drift apart.
static_assert(eternalsonata::kCharwordsBase == 0x8b001800,
              "charwords moved; regenerate the relocation hooks");
static_assert(0x8b001800 + 24 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "charwords (12 * 2 bytes) does not fit the reserved page");
static_assert(eternalsonata::kSlotbytesBase == 0x8b000000,
              "slotbytes moved; regenerate the relocation hooks");
static_assert(0x8b000000 + 12 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "slotbytes (12 * 1 bytes) does not fit the reserved page");
static_assert(eternalsonata::kStatsBaseBase == 0x8b000100,
              "stats_base moved; regenerate the relocation hooks");
static_assert(0x8b000100 + 576 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "stats_base (12 * 48 bytes) does not fit the reserved page");
static_assert(eternalsonata::kTemplateBase == 0x8b001000,
              "template moved; regenerate the relocation hooks");
static_assert(0x8b001000 + 1632 <= eternalsonata::kRelocationBase + eternalsonata::kRelocationSize,
              "template (12 * 136 bytes) does not fit the reserved page");
static_assert(eternalsonata::kRelocatedCharacterCount == 12,
              "the hook table was generated for a different cast size");

}  // namespace

// The hook bodies are looked up by name by the recompiler, so they
// keep external linkage.

// charwords: 0x824400c8 -> 0x8b001800
constexpr int32_t kRelocCharwordsDelta = static_cast<int32_t>(0x08bc1738);

void PartyReloc_charwords_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocCharwordsDelta;
}

// slotbytes: 0x8243fc30 -> 0x8b000000
constexpr int32_t kRelocSlotbytesDelta = static_cast<int32_t>(0x08bc03d0);

void PartyReloc_slotbytes_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocSlotbytesDelta;
}

void PartyReloc_slotbytes_Shift(PPCRegister& reg) {
    reg.u32 += kRelocSlotbytesDelta;
}

void PartyReloc_slotbytes_Unshift(PPCRegister& reg) {
    reg.u32 -= kRelocSlotbytesDelta;
}

// stats_base: 0x8243fee8 -> 0x8b000100
constexpr int32_t kRelocStatsBaseDelta = static_cast<int32_t>(0x08bc0218);

void PartyReloc_stats_base_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocStatsBaseDelta;
}

// template: 0x82016150 -> 0x8b001000
constexpr int32_t kRelocTemplateDelta = static_cast<int32_t>(0x08feaeb0);

void PartyReloc_template_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocTemplateDelta;
}

// stats_base loop bound: 0x824400c8 -> 0x8b000340 (the end of the relocated array, two entries longer)
constexpr int32_t kRelocEndStatsBaseDelta = static_cast<int32_t>(0x08bc0278);

void PartyRelocEnd_stats_base_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kRelocEndStatsBaseDelta;
}

// position loop bound: 0x8243fc30 -> 0x8243fc38 (two more entries)
constexpr int32_t kBoundPositionDelta = static_cast<int32_t>(0x00000008);

void PartyBound_position_Remap(PPCRegister& reg) {
    // fired after the addi, so reg holds the finished old address
    reg.u32 += kBoundPositionDelta;
}
